language: python
python:
  - "2.7"
  - "3.4"

install: "pip install -r requirements.txt"
before_script:
  - "pep8 --ignore=E501 django_jsonp/"
# command to run tests
script: coverage run --source django_jsonp tests/./manage.py test

after_success:
  coveralls